"""eBay Sold Listings Scraper — 抓取球星卡真实成交价格数据。

第一性目的:
    获取 NBA 球星卡在 eBay 上的已售记录（成交价、日期、拍卖/一口价）。
    这是整个投资 Agent 的"价格眼睛"——后续的价格趋势分析、RSI 计算、
    卖出信号判断全部依赖这里的成交数据。

整体架构:
    EbayScraper 类分为 4 层:
    1. HTTP 请求层 (_get_page)      — 负责发请求，处理反爬、重试、速率控制
    2. HTML 解析层 (_parse_*)       — 负责从 HTML 提取结构化数据
    3. 业务逻辑层 (get_sold_listings) — 负责搜索、翻页、日期过滤
    4. 持久化层   (save_sales)       — 负责写入 card_sales 表并去重

数据流:
    搜索关键词 → 拼接 eBay URL → 逐页抓取 HTML → 解析每条记录
    → 过滤无效/超期条目 → 返回 SaleRecord 列表 → 写入数据库

Usage:
    scraper = EbayScraper()
    sales = scraper.get_sold_listings(
        player="Victor Wembanyama",
        series="Prizm",
        parallel="Silver",
        grade="PSA 10",
        days=30,
    )
    scraper.save_sales("Victor Wembanyama", "Prizm", "Silver", "PSA 10", sales)

CLI:
    python -m rookiecard.scrapers.ebay --player "Victor Wembanyama" --series "Prizm"
"""

import re
import time
import random
import logging
from dataclasses import dataclass
from datetime import datetime, timedelta
from urllib.parse import quote_plus

from curl_cffi import requests as curl_requests
from bs4 import BeautifulSoup

from rookiecard.config import Config
from rookiecard.db.connection import get_db

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------

# User-Agent 轮换池：模拟不同浏览器，降低被识别为爬虫的概率
USER_AGENTS = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
]

# eBay 搜索基础 URL
# LH_Complete=1 & LH_Sold=1 → 只看已售/已完成的商品
# _sop=13 → 按结束时间排序（最新在前）
EBAY_BASE_URL = "https://www.ebay.com/sch/i.html"
EBAY_HOME_URL = "https://www.ebay.com/"

# 模拟 Chrome 131 的完整请求头（含 sec-ch-ua 系列，通过 TLS 指纹 + 请求头双重伪装）
DEFAULT_HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "max-age=0",
    "Sec-Ch-Ua": '"Chromium";v="131", "Not_A Brand";v="24"',
    "Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": '"macOS"',
    "Sec-Fetch-Dest": "document",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-Site": "same_origin",
    "Sec-Fetch-User": "?1",
    "Upgrade-Insecure-Requests": "1",
}

# eBay 被动/主动反爬时页面里常见的提示词
BLOCKED_PAGE_PATTERNS = (
    "pardon our interruption",
    "to continue, please verify",
    "captcha",
    "robot check",
    "enable javascript and cookies",
    "generated by cloudflare",
)


# ---------------------------------------------------------------------------
# 数据类
# ---------------------------------------------------------------------------


@dataclass
class SaleRecord:
    """一条 eBay 已售记录。

    Attributes:
        title:        商品标题（含卡片描述信息）
        price:        成交价，单位 USD
        date:         成交日期，ISO 格式 "2026-01-15"
        listing_type: "auction"（竞拍） 或 "buy_it_now"（一口价）
        url:          eBay 商品页链接，用于去重（card_sales 表的唯一键）
        seller:       卖家 ID
        image_url:    商品图片链接
    """
    title: str
    price: float
    date: str
    listing_type: str
    url: str
    seller: str = ""
    image_url: str = ""


# ---------------------------------------------------------------------------
# 核心类: EbayScraper
# ---------------------------------------------------------------------------


class EbayScraper:
    """eBay 已售列表爬虫。

    设计原则:
    - 每次 HTTP 请求间隔 delay + 随机 0~2 秒，避免触发反爬
    - 随机轮换 User-Agent
    - 使用 httpx.Client 保持会话 Cookie
    - 所有解析方法为 staticmethod，方便单独测试
    """

    def __init__(
        self,
        delay: float | None = None,
        max_pages: int | None = None,
        max_retries: int | None = None,
        timeout: float | None = None,
    ):
        """
        Args:
            delay:       每次请求的最小间隔秒数（默认取 Config.EBAY_DELAY = 3.0）
            max_pages:   最多翻几页（每页约 60 条，3 页 ≈ 180 条）
            max_retries: 单次请求的最大重试次数
        """
        self.delay = delay if delay is not None else Config.EBAY_DELAY
        self.max_pages = max_pages if max_pages is not None else Config.EBAY_MAX_PAGES
        self.max_retries = max_retries if max_retries is not None else Config.EBAY_MAX_RETRIES
        self.timeout = timeout if timeout is not None else Config.EBAY_TIMEOUT
        self._last_request_time = 0.0  # 上次请求的时间戳，用于速率控制
        self._session_warmed = False
        # 整个会话固定一个 UA，避免同 session 内 UA 变化被检测
        self._user_agent = random.choice(USER_AGENTS)
        self._client = self._build_client()

    def _build_client(self) -> curl_requests.Session:
        """构建 curl_cffi Session，模拟 Chrome 的 TLS 指纹（JA3/JA4）。

        curl_cffi 的核心优势：底层使用 curl-impersonate，
        能精确复现 Chrome 的 TLS ClientHello、HTTP/2 SETTINGS 帧、
        HPACK 头压缩顺序等特征，从而绕过基于 TLS 指纹的反爬。
        """
        session = curl_requests.Session(
            impersonate="chrome131",  # 模拟 Chrome 131 的完整 TLS 指纹
            headers=DEFAULT_HEADERS,
            timeout=self.timeout,
        )
        if Config.EBAY_PROXY_URL:
            session.proxies = {
                "http": Config.EBAY_PROXY_URL,
                "https": Config.EBAY_PROXY_URL,
            }
        return session

    def close(self) -> None:
        """显式关闭底层连接池。"""
        self._client.close()

    def __del__(self) -> None:
        try:
            self.close()
        except Exception:
            pass

    def _reset_client(self) -> None:
        """在遇到 503 / challenge 页后重建会话（清除被标记的 cookie + 换新 UA）。"""
        try:
            self._client.close()
        except Exception:
            pass
        self._user_agent = random.choice(USER_AGENTS)
        self._client = self._build_client()
        self._session_warmed = False

    def _build_headers(self, referer: str | None = None) -> dict[str, str]:
        """构建单次请求头，保持会话内 UA 一致。"""
        headers = {
            "User-Agent": self._user_agent,
            "Referer": referer or EBAY_HOME_URL,
        }
        return headers

    @staticmethod
    def _looks_blocked(html: str) -> bool:
        """检测是否命中了 challenge / 反爬页面。"""
        if not html:
            return False
        lowered = html.lower()
        return any(pattern in lowered for pattern in BLOCKED_PAGE_PATTERNS)

    def _warm_up_session(self) -> None:
        """先访问首页获取 cookie，模拟真实用户从首页进入搜索的行为。"""
        if self._session_warmed:
            return
        try:
            # 首页请求用 Sec-Fetch-Site: none（直接在地址栏打开）
            warmup_headers = self._build_headers()
            warmup_headers["Sec-Fetch-Site"] = "none"
            resp = self._client.get(
                EBAY_HOME_URL,
                headers=warmup_headers,
                allow_redirects=True,
            )
            self._last_request_time = time.time()
            resp.raise_for_status()
            self._session_warmed = True
            # warm-up 后等一下，模拟用户浏览首页后再搜索
            time.sleep(random.uniform(1.5, 3.0))
        except Exception as exc:
            logger.debug("eBay session warm-up failed: %s", exc)

    def _get_page_with_playwright(self, url: str) -> str:
        """在 curl_cffi 连续失败后，用真实浏览器 + stealth 插件回退抓取一次。"""
        try:
            from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
            from playwright.sync_api import sync_playwright
        except ImportError as exc:
            raise RuntimeError("Playwright fallback is not installed") from exc

        try:
            from playwright_stealth import stealth_sync
        except ImportError:
            stealth_sync = None

        try:
            with sync_playwright() as playwright:
                launch_kwargs = {
                    "headless": True,
                    "args": [
                        "--disable-blink-features=AutomationControlled",
                        "--no-sandbox",
                    ],
                }
                if Config.EBAY_PLAYWRIGHT_PROXY_URL:
                    launch_kwargs["proxy"] = {"server": Config.EBAY_PLAYWRIGHT_PROXY_URL}

                browser = playwright.chromium.launch(**launch_kwargs)
                try:
                    context = browser.new_context(
                        user_agent=random.choice(USER_AGENTS),
                        locale="en-US",
                        viewport={"width": 1440, "height": 900},
                        extra_http_headers={"Accept-Language": "en-US,en;q=0.9"},
                    )
                    try:
                        page = context.new_page()

                        # 注入 stealth 脚本：隐藏 navigator.webdriver、
                        # 伪造 plugins/languages/WebGL 等浏览器指纹
                        if stealth_sync is not None:
                            stealth_sync(page)

                        timeout_ms = int(max(self.timeout, 20.0) * 1000)

                        page.goto(EBAY_HOME_URL, wait_until="domcontentloaded", timeout=timeout_ms)
                        page.wait_for_timeout(1500)

                        response = page.goto(url, wait_until="domcontentloaded", timeout=timeout_ms)
                        page.wait_for_timeout(2500)

                        if response and response.status in {429, 500, 502, 503, 504}:
                            raise RuntimeError(f"Playwright got HTTP {response.status}")

                        html = page.content()
                        if self._looks_blocked(html):
                            raise RuntimeError("Playwright also hit an anti-bot challenge")

                        return html
                    finally:
                        context.close()
                finally:
                    browser.close()
        except PlaywrightTimeoutError as exc:
            raise RuntimeError(f"Playwright timed out for {url}") from exc

    # ===================================================================
    # 第 1 层: HTTP 请求
    # ===================================================================

    def _get_page(self, url: str) -> str:
        """发送 HTTP GET 请求并返回 HTML 文本。

        逻辑:
        1. 计算距上次请求的时间差，不足 delay 则 sleep 补齐
        2. 在 delay 基础上加 0~2 秒随机抖动，模拟人类行为
        3. 随机选一个 User-Agent
        4. 用 curl_cffi 发请求（模拟 Chrome TLS 指纹、自动跟随重定向、保持 Cookie）
        5. 失败时指数退避重试

        Returns:
            HTML 文本字符串

        Raises:
            RuntimeError: 重试耗尽后仍失败
        """
        from curl_cffi import CurlError

        self._warm_up_session()
        last_error: Exception | None = None

        for attempt in range(self.max_retries):
            try:
                # --- 速率控制 ---
                elapsed = time.time() - self._last_request_time
                wait = self.delay - elapsed + random.uniform(0, 2)
                if wait > 0:
                    time.sleep(wait)

                resp = self._client.get(
                    url,
                    headers=self._build_headers(referer=EBAY_HOME_URL),
                    allow_redirects=True,
                )
                self._last_request_time = time.time()

                if resp.status_code in {429, 500, 502, 503, 504}:
                    raise RuntimeError(f"transient HTTP status {resp.status_code}")

                resp.raise_for_status()

                if self._looks_blocked(resp.text):
                    raise RuntimeError("eBay anti-bot challenge detected")

                return resp.text

            except CurlError as e:
                # curl_cffi 的网络/超时错误（对应 httpx 的 TimeoutException/NetworkError）
                last_error = e
                backoff = self.delay + (2 ** attempt) + random.uniform(1, 3)
                logger.warning(
                    "eBay request failed (attempt %d/%d): %s. Retrying in %.1fs...",
                    attempt + 1, self.max_retries, e, backoff,
                )
                self._reset_client()
                time.sleep(backoff)
            except RuntimeError as e:
                last_error = e
                backoff = self.delay + (2 ** attempt) + random.uniform(3, 8)
                logger.warning(
                    "eBay error (attempt %d/%d): %s. Retrying in %.1fs...",
                    attempt + 1, self.max_retries, e, backoff,
                )
                self._reset_client()
                time.sleep(backoff)

        if Config.EBAY_USE_PLAYWRIGHT_FALLBACK:
            try:
                logger.info("curl_cffi exhausted, trying Playwright+stealth fallback for %s", url)
                return self._get_page_with_playwright(url)
            except Exception as fallback_error:
                raise RuntimeError(
                    f"Failed to fetch {url} after {self.max_retries} retries; "
                    f"last_error={last_error}; playwright_fallback={fallback_error}"
                ) from fallback_error

        raise RuntimeError(f"Failed to fetch {url} after {self.max_retries} retries; last_error={last_error}")

    # ===================================================================
    # 第 2 层: HTML 解析
    # ===================================================================

    @staticmethod
    def parse_price(text: str) -> float | None:
        """从价格文本中提取数值。

        处理的格式:
        - "$123.45"       → 123.45
        - "$1,234.56"     → 1234.56
        - "C $85.00"      → 85.00   （加元等其他币种前缀）
        - "$100.00 to $200.00" → 100.00 （取区间最低价）
        - "Free"          → None    （无效）

        逻辑:
        1. 用正则 \\d[\\d,]*\\.?\\d* 匹配第一个数字串
        2. 去掉逗号
        3. 转为 float
        """
        if not text:
            return None
        # 匹配第一个看起来像价格的数字（整数部分可能有逗号，小数部分可选）
        match = re.search(r"(\d[\d,]*\.?\d*)", text)
        if not match:
            return None
        price_str = match.group(1).replace(",", "")
        try:
            return float(price_str)
        except ValueError:
            return None

    @staticmethod
    def parse_date(text: str) -> str | None:
        """从日期文本中提取 ISO 日期。

        eBay 的日期格式不统一，常见的有:
        - "Sold  Jan 15, 2026"  → "2026-01-15"
        - "Sold  1/15/2026"     → "2026-01-15"
        - "Jan 15, 2026"        → "2026-01-15"

        逻辑:
        1. 去掉 "Sold" 前缀和多余空格
        2. 依次尝试多种日期格式解析
        3. 返回 ISO 格式字符串
        """
        if not text:
            return None

        # 清理文本
        cleaned = re.sub(r"(?i)sold\s*", "", text).strip()

        # 尝试多种格式
        formats = [
            "%b %d, %Y",    # "Jan 15, 2026"
            "%B %d, %Y",    # "January 15, 2026"
            "%m/%d/%Y",     # "1/15/2026"
            "%b-%d-%y",     # "Jan-15-26"
            "%d-%b-%Y",     # "15-Jan-2026"
        ]
        for fmt in formats:
            try:
                dt = datetime.strptime(cleaned, fmt)
                return dt.strftime("%Y-%m-%d")
            except ValueError:
                continue

        return None

    @staticmethod
    def parse_listing_type(item_soup: BeautifulSoup) -> str:
        """判断一条记录是竞拍还是一口价。

        判断依据（按优先级）:
        1. 如果包含 "Best offer accepted" → "buy_it_now"
        2. 如果包含 "Buy It Now" 文本   → "buy_it_now"
        3. 如果包含 "bids" 文本          → "auction"
        4. 默认                           → "auction"

        eBay 页面结构中，listing type 信息散布在多个位置，
        所以我们用全文搜索关键词的方式判断。
        """
        text = item_soup.get_text(separator=" ", strip=True).lower()
        if "best offer accepted" in text:
            return "buy_it_now"
        if "buy it now" in text:
            return "buy_it_now"
        if "bid" in text:
            return "auction"
        return "auction"

    def _parse_results_page(self, html: str) -> list[SaleRecord]:
        """解析一整页 eBay 搜索结果 HTML，提取所有已售记录。

        eBay 搜索结果页的 DOM 结构（2025+ 新版 s-card）:
        <ul class="srp-results">
          <li class="s-card">                          ← 每条记录
            <a class="s-card__link" href="...">        ← 商品链接（含 /itm/）
            <span class="s-card__title">               ← 标题
            <span class="s-card__price">               ← 价格
            <span class="positive">                    ← "Sold  Mar 29, 2026"
            <img class="s-card__image">                ← 图片
          旧版使用 li.s-item + s-item__* 选择器，此方法同时兼容两种结构。

        逻辑:
        1. 优先用 li.s-card（新版），回退到 li.s-item（旧版）
        2. 对每个元素提取 url, title, price, date, listing_type
        3. 过滤掉广告（"Shop on eBay"）和缺少关键字段的条目
        4. 返回有效的 SaleRecord 列表
        """
        soup = BeautifulSoup(html, "html.parser")

        # 新版用 s-card，旧版用 s-item，优先新版
        items = soup.select("li.s-card")
        if not items:
            items = soup.select("li.s-item")
        records = []

        for item in items:
            # --- URL ---
            # 查找包含 /itm/ 的链接（真实商品页，排除广告）
            url = None
            for link_tag in item.select("a[href*='/itm/']"):
                url = link_tag.get("href", "")
                break
            if not url:
                continue

            # 去掉 URL 中的跟踪参数，只保留到 item ID
            if "?" in url:
                url = url.split("?")[0]

            # --- 标题 ---
            # 新版: .s-card__title, 旧版: div.s-item__title
            title_tag = (
                item.select_one(".s-card__title")
                or item.select_one("div.s-item__title")
                or item.select_one("span.s-item__title")
            )
            title = title_tag.get_text(strip=True) if title_tag else ""
            # 去掉尾部 "Opens in a new window or tab"
            title = re.sub(r"Opens in.*$", "", title).strip()
            # 跳过广告条目
            if not title or "shop on ebay" in title.lower():
                continue

            # --- 价格 ---
            # 新版: span.s-card__price, 旧版: span.s-item__price
            price_tag = (
                item.select_one("span.s-card__price")
                or item.select_one("span.s-item__price")
            )
            price_text = price_tag.get_text(strip=True) if price_tag else ""
            price = self.parse_price(price_text)
            if price is None:
                continue

            # --- 日期 ---
            # 新版: span.positive 含 "Sold  Mar 29, 2026"
            # 旧版: span.POSITIVE / span.s-item__ended-date
            date_str = None
            for selector in ["span.positive", "span.POSITIVE",
                             "span.s-item__ended-date", "span.s-item__endedDate"]:
                date_tag = item.select_one(selector)
                if date_tag:
                    text = date_tag.get_text(strip=True)
                    if "sold" in text.lower() or "Sold" in text:
                        date_str = self.parse_date(text)
                        if date_str:
                            break

            # 回退: 搜索任何含 "Sold" 的文本节点
            if not date_str:
                for el in item.find_all(string=lambda t: t and "Sold" in t):
                    date_str = self.parse_date(el.strip())
                    if date_str:
                        break

            if not date_str:
                date_str = datetime.now().strftime("%Y-%m-%d")

            # --- Listing 类型 ---
            listing_type = self.parse_listing_type(item)

            # --- 卖家 ---
            seller_tag = (
                item.select_one("span.s-item__seller-info-text")
                or item.select_one(".s-card__seller")
            )
            seller = seller_tag.get_text(strip=True) if seller_tag else ""

            # --- 图片 ---
            img_tag = (
                item.select_one("img.s-card__image")
                or item.select_one("img.s-item__image-img")
            )
            image_url = ""
            if img_tag:
                image_url = img_tag.get("src", "") or img_tag.get("data-defer-load", "")

            records.append(SaleRecord(
                title=title,
                price=price,
                date=date_str,
                listing_type=listing_type,
                url=url,
                seller=seller,
                image_url=image_url,
            ))

        return records

    # ===================================================================
    # 第 3 层: 业务逻辑
    # ===================================================================

    @staticmethod
    def _build_search_url(player: str, series: str = "", parallel: str = "",
                          grade: str = "", page: int = 1) -> str:
        """拼接 eBay 已售列表的搜索 URL。

        搜索词构成: "{player} {series} {parallel} {grade} rookie card"
        URL 参数:
        - _nkw:        搜索关键词（URL 编码）
        - LH_Complete: 1 = 只看已完成的交易
        - LH_Sold:     1 = 只看已售出的商品
        - _sop:        13 = 按结束时间排序（最新在前）
        - _pgn:        页码（从 1 开始）

        Example:
            _build_search_url("Victor Wembanyama", "Prizm", "Silver", "PSA 10")
            → "https://www.ebay.com/sch/i.html?_nkw=Victor+Wembanyama+Prizm+Silver+PSA+10+rookie+card&LH_Complete=1&LH_Sold=1&_sop=13&_pgn=1"
        """
        parts = [player]
        if series:
            parts.append(series)
        if parallel:
            parts.append(parallel)
        if grade:
            parts.append(grade)
        parts.append("rookie card")

        query = quote_plus(" ".join(parts))
        return f"{EBAY_BASE_URL}?_nkw={query}&LH_Complete=1&LH_Sold=1&_sop=13&_pgn={page}"

    @staticmethod
    def _build_search_url_raw(search_query: str, page: int = 1) -> str:
        """用用户提供的精确搜索词构建 eBay 已售列表 URL。

        与 _build_search_url 不同，这里直接使用用户从 eBay 扫描得到的
        精确标题作为搜索词，不做任何拼接，确保搜索结果精准匹配。
        """
        query = quote_plus(search_query)
        return f"{EBAY_BASE_URL}?_nkw={query}&LH_Complete=1&LH_Sold=1&_sop=13&_pgn={page}"

    def get_sold_listings(
        self,
        player: str = "",
        series: str = "",
        parallel: str = "",
        grade: str = "",
        days: int = 30,
        search_query: str = "",
    ) -> list[SaleRecord]:
        """抓取指定球星卡的 eBay 已售记录。这是对外的主入口方法。

        两种搜索模式:
        - 精确模式: 传入 search_query（来自用户扫描 eBay 得到的精确标题），直接用它搜索
        - 组合模式: 传入 player/series/parallel/grade，拼接为搜索词

        逻辑:
        1. 构建搜索 URL
        2. 逐页抓取（page 1, 2, ... 直到 max_pages）
        3. 解析每页得到 SaleRecord 列表
        4. 日期过滤: 只保留最近 days 天内的记录
        5. 终止条件（满足任一即停止翻页）:
           a. 当前页无结果
           b. 当前页最后一条记录已超出 days 天范围
           c. 已达到 max_pages 页数上限

        Args:
            player:       球员姓名 (e.g. "Victor Wembanyama")
            series:       卡片系列 (e.g. "Prizm", "Select")
            parallel:     卡片版本 (e.g. "Silver", "Base")
            grade:        评级 (e.g. "PSA 10", "Raw")
            days:         只获取最近 N 天的成交记录
            search_query: 精确搜索词（优先使用，非空时忽略 player/series/parallel/grade）

        Returns:
            list[SaleRecord] 按日期倒序排列
        """
        cutoff = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
        all_sales: list[SaleRecord] = []

        for page in range(1, self.max_pages + 1):
            if search_query:
                url = self._build_search_url_raw(search_query, page)
            else:
                url = self._build_search_url(player, series, parallel, grade, page)
            logger.info("Fetching page %d: %s", page, url)

            try:
                html = self._get_page(url)
            except RuntimeError as e:
                logger.error("Failed to fetch page %d: %s", page, e)
                break

            records = self._parse_results_page(html)
            if not records:
                logger.info("No results on page %d, stopping.", page)
                break

            # 日期过滤 + 检查是否超出范围
            page_has_valid = False
            for rec in records:
                if rec.date >= cutoff:
                    all_sales.append(rec)
                    page_has_valid = True

            # 如果本页最后一条记录已超出时间范围，后续页只会更旧，停止翻页
            if not page_has_valid:
                logger.info("All records on page %d are older than %d days, stopping.", page, days)
                break

            logger.info("Page %d: %d records collected.", page, len(records))

        # 按日期倒序排列
        all_sales.sort(key=lambda s: s.date, reverse=True)
        logger.info("Total: %d sales in last %d days.", len(all_sales), days)
        return all_sales

    # ===================================================================
    # 第 4 层: 数据库持久化
    # ===================================================================

    def save_sales(
        self,
        player_name: str,
        series: str,
        parallel: str,
        grade: str,
        sales: list[SaleRecord],
        db_path: str = None,
    ) -> int:
        """将已售记录写入 card_sales 表。

        逻辑:
        1. 通过 player_name 在 players 表中查找 player_id
           - 如果球员不存在，跳过并发出警告
        2. 对每条 SaleRecord 执行 INSERT OR IGNORE
           - card_sales 表的 UNIQUE(url) 约束自动去重
           - 相同 URL 的记录不会被重复插入
        3. 返回实际新增的行数

        Args:
            player_name: 球员姓名，必须已存在于 players 表
            series:      卡片系列 (写入 card_sales.series)
            parallel:    卡片版本 (写入 card_sales.parallel)
            grade:       评级 (写入 card_sales.grade)
            sales:       SaleRecord 列表
            db_path:     数据库路径（None 则使用默认）

        Returns:
            int: 新增行数
        """
        if not sales:
            return 0

        with get_db(db_path) as conn:
            # 查找 player_id
            row = conn.execute(
                "SELECT id FROM players WHERE name = ?", (player_name,)
            ).fetchone()
            if not row:
                logger.warning("Player '%s' not found in DB, skipping save.", player_name)
                return 0
            player_id = row["id"]

            # 记录插入前的行数，用于计算新增数
            before = conn.execute("SELECT COUNT(*) FROM card_sales").fetchone()[0]

            for sale in sales:
                conn.execute(
                    """INSERT OR IGNORE INTO card_sales
                       (player_id, series, parallel, grade, price, sale_date,
                        listing_type, platform, url)
                       VALUES (?, ?, ?, ?, ?, ?, ?, 'ebay', ?)""",
                    (
                        player_id, series, parallel, grade,
                        sale.price, sale.date, sale.listing_type, sale.url,
                    ),
                )

            after = conn.execute("SELECT COUNT(*) FROM card_sales").fetchone()[0]
            inserted = after - before

        logger.info("Saved %d new sales for %s (skipped %d duplicates).",
                     inserted, player_name, len(sales) - inserted)
        return inserted


# ---------------------------------------------------------------------------
# CLI 入口: python -m rookiecard.scrapers.ebay
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=getattr(logging, Config.LOG_LEVEL),
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    parser = argparse.ArgumentParser(description="Scrape eBay sold listings for NBA rookie cards")
    parser.add_argument("--player", required=True, help="Player name, e.g. 'Victor Wembanyama'")
    parser.add_argument("--series", default="Prizm", help="Card series (default: Prizm)")
    parser.add_argument("--parallel", default="", help="Card parallel, e.g. 'Silver'")
    parser.add_argument("--grade", default="", help="Card grade, e.g. 'PSA 10'")
    parser.add_argument("--days", type=int, default=30, help="Days of history (default: 30)")
    parser.add_argument("--save", action="store_true", help="Save results to database")
    args = parser.parse_args()

    scraper = EbayScraper()
    sales = scraper.get_sold_listings(
        player=args.player,
        series=args.series,
        parallel=args.parallel,
        grade=args.grade,
        days=args.days,
    )

    print(f"\nFound {len(sales)} sold listings:\n")
    for s in sales[:10]:  # 只展示前 10 条
        print(f"  ${s.price:>8.2f}  {s.date}  [{s.listing_type:>10}]  {s.title[:60]}")
    if len(sales) > 10:
        print(f"  ... and {len(sales) - 10} more")

    if args.save:
        from rookiecard.db.migrate import create_tables
        from pathlib import Path

        Path(Config.DB_PATH).parent.mkdir(parents=True, exist_ok=True)
        create_tables()
        n = scraper.save_sales(args.player, args.series, args.parallel, args.grade, sales)
        print(f"\nSaved {n} new records to database.")
